### ISSUE TITLE
Enabling WiFi in the rig

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/odm360#102]
The parent pi should provide the WiFi for the rig. We need to enable this in the deployment scripts, e.g.:
https://learn.sparkfun.com/tutorials/setting-up-a-raspberry-pi-3-as-an-access-point/all

**Comment by hcwinsemius** [comment]
Good catch! We do need the rig to also be able to connect to WiFi networks so that data can be exchanged over wifi. This post might help to list WiFi networks and connect to them.

https://raspberrypi.stackexchange.com/questions/69084/wi-fi-scanning-and-displaying-using-python-run-by-php

**Comment by smathermather** [comment]
I'm thinking out loud a bit, but I lean toward having the parent pi be the WiFi hub by default -- or maybe it's a config setting to make it the wifi hub. In this way, we can streamline the child pi connections and ensure connectivity. It also isolates the traffic to just the collection of devices: wifi usage on a network shared by other processes could create bottle necks and timing issue which could affect a cascade of issues.

**Comment by smathermather** [comment]
As I am thinking about this further, and in concert with https://github.com/OpenDroneMap/odm360/issues/106, I think we need a separate (USB?) NIC for the parent pi. In that way, the parent can communicate with the child pis on it's own network (built in NIC) and separately be patched into an internet connected WiFi (second NIC). A good USB WiFi connection which maxes out the USB3 connections is ~$15-25 and quite performant.

**Comment by hcwinsemius** [comment]
I am not sure if this is needed. Having isolated wifi for parent child comms sounds oerfect to me. And...I am pretty sure that a raspi can make a WiFi and at the same be connected to a second network environment. I am not totally confident about this though.

**Comment by hcwinsemius** [comment]
Checking it a bit better: we can just use the ethernet for this purpose for starters. If a user wants a wifi connection then I guess we need a second wifi.

**Comment by smathermather** [comment]
I like the idea of having an isolated network and a bit of control over it. I could see a common use case in the field where a second wifi card would be useful for e.g. connecting to a cellular hot spot. But it need not be default, though we should design for it.
