### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by hcwinsemius** [OpenDroneMap/odm360#104]
An end point for retrieving, modifying and storing rig settings is needed. Some things that are needed:
[ ] ublox settings such as port baud rate and so on
[ ] WiFi settings (search for networks and addnetwork to known networks)
[ ] log detail (info/debug)

**Comment by smathermather** [comment]
Yup. See my updates to the WiFi issues here: https://github.com/OpenDroneMap/odm360/issues/102
