### ISSUE TITLE
Method for killing gphoto2 processes

### ISSUE THREAD

**Issue by hcwinsemius** [OpenDroneMap/odm360#15]
It seems that gphoto2 sometimes doesn't gracefully close. I propose to add a killall (using psutil) to any gphoto2 processes in the CameraRig class in case gphoto2 is used as intermediate between controller and camera device. In case picamera is used this is not relevant.

**Comment by smathermather** [comment]
This doesn't surprise me. I note that Gabriel had a process for killing gphoto.
