### ISSUE TITLE
child pis not reconnecting to parent wifi

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/odm360#154]
If we set up a child pi with a wpa_supplicant to connect to, say the home network, do all our update and install process, and deploy the parent and child pis, everything works pretty smoothly. The child pi finds the original wifi network if the parent wifi isn't available, and connects to the parent wifi without a problem if it's there on boot.

However, if the children are connected to the parent wifi and the parent is rebooted or otherwise the parent wifi is temporarily removed, the children will connect back with the backup network (which is good) but not pick up the parent wifi network again when that becomes available.

**Comment by hcwinsemius** [comment]
I misunderstood the problem on whatsapp. I have already made sure in provisioning that wpa_supplicant.conf contains the parent pi AP and that it is prioritized over other APs. However, if you are already connected to a wlan and then the parent AP comes available, there is no reason for the child to swap networks. I guess that is the reason why it doesn't work as you expected.

My idea about the pi installation is to 
- connect a network cable to the parent, voila internet available to parent and to all children (I have set up parent as a bridge router)
- then get the children updated via the passed-on internet of the parent.
That prevents that you need any additional wpa_supplicant additions.

Can you try that?

**Comment by smathermather** [comment]
I could, but that still seems brittle. How do the children connect to the parent? Shouldn't they be able to connect to the parent regardless of network?

**Comment by smathermather** [comment]
I'll reopen if this continues to be an issue.
