### ISSUE TITLE
Set up timing tester system

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/odm360#19]
Includes building a clock to record

**Comment by smathermather** [comment]
https://www.instructables.com/id/High-speed-Clock-for-Slow-motion-Videos/

**Comment by GabrielMaguire** [comment]
Timer prototype completed. The Arduino Nano writes the digits sequentially to the display, so the necessary delay in code to capture all 4 digits is a function of the camera’s shutter speed. For my iPhone, a 5ms delay allowed me to clearly capture the display output time.

![545DBA6F-08DB-4C37-80FF-471992011007](https://user-images.githubusercontent.com/39974571/93810844-3748f200-fc1d-11ea-9325-5727f3fc70c7.jpeg)

**Comment by smathermather** [comment]
w00t!

Ok, so there are a few things we want to test: We want to understand across the pi camera's sensor what the rolling shutter timing (and shape) is. And for a collection of pi cameras, we want to understand how close the firing time is between the cameras. These two will give us a sense of what our error will be.

I will close this issue and open the related one.
