### ISSUE TITLE
Own images

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/odm360#24]
This doc is good: https://github.com/OpenDroneMap/odm360/blob/master/examples/setup_pi.md. Working through it at the moment. Ultimately we might want our own images with nominal changes: e.g. setting host names for each of the pi zeros so folks don't have to search their network for headless pi zeros.

**Comment by hcwinsemius** [comment]
Agreed. I would opt for the central raspi to be host for the children. If
we make prefab images that should be easy. We can even let a smart phone
login to that for logging msgs to the smartphone.

Op za 4 jul. 2020 22:30 schreef Stephen Mather <notifications@github.com>:

**Comment by smathermather** [comment]
Love it. Yes, the wifi network should be established by the central raspi. In reality, the child images could be all the same, but the parent raspi could configure and differentiate them.

**Comment by hcwinsemius** [comment]
We need to distinguish them indeed. Each cam can get a nr and that can be
used in their resp. logs and name of photo folder.

Op zo 5 jul. 2020 00:31 schreef Stephen Mather <notifications@github.com>:

**Comment by ivangayton** [comment]
Over the weekend I've been working on provisioning Pi's. Obviously I need to do that to set up the NTP server, but the way I've designed my setup, it starts with a fairly generic image; raspberry Pi OS with basic networking, serial ports enabled, and the dependencies for ODM 360 set up. I'm doing this fairly carefully to ensure a nice, lightweight, robust image.

You'll see a couple of markdown files and a script and the examples directory (Steve, you might be already using it to set up your zeros). Once I get a little further, I'll set up a branch for provisioning, that includes a new directory for all that stuff, and submit it as a pull request.

Therefore it should be possible to Snapchat that image, flash multiple cards exactly the same way, and configure them all with scripts, which can indeed be coordinated by the parent.
