### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by hcwinsemius** [OpenDroneMap/odm360#4]
The project needs some restructuring. Suggested folder structure:

- README.md
- setup.py (pip installer)
- __init__.py
- environment.yml (for conda virtual env)
- folder: odm360 (code base)
- folder: tests (test code)
- folder: examples (example code)

**Comment by ivangayton** [comment]
Strongly agree.

Also a license file; I don't see one?

**Comment by hcwinsemius** [comment]
wanted to discuss this. I often use MIT but want to leave this to @smathermather to decide.

**Comment by smathermather** [comment]
Yes, a license file is a bit critical. I am ornery and default to GPL, but MIT is fine. :)  It'd be good to know if @GabrielMaguire has an opinion.

**Comment by hcwinsemius** [comment]
Just checked gphoto2. This is GPL so we have to do GPL. @smathermather if you agree can you add the license? Also in the setup.py plz

**Comment by smathermather** [comment]
In my IANAL opinion, we are only constrained by the GPL is we binary compile to gphoto2. Even less so if we are using the lGPL lib-gphoto. Much as we can run non-GPL software on Linux.

**Comment by smathermather** [comment]
FWIW, I had @GabrielMaguire make the call on license and he went liberal on it.
