### ISSUE TITLE
Provisioning infrastructure

### ISSUE THREAD

**Issue by ivangayton** [OpenDroneMap/odm360#5]
I don't see where it's noted what distro is being used (I assume Raspbian, but could be something else). It's always nice to explicitly standardize the environment.

I'm a fan of .deb files to do that; this way anyone can start with a given widely-available distro and chuck in a .deb archive to get right up to speed; saves users a lot of downloading if they're in a place with crap internet.

**Comment by hcwinsemius** [comment]
I guess Raspbian indeed. I am proposing a miniconda environment to quickly get all libs that you need. See issue #4
