### ISSUE TITLE
Create example foreign table registration example

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/odm360#57]
See https://github.com/OpenDroneMap/odm360/pull/50 as starting place.

**Comment by smathermather** [comment]
Documentation on Postgres FDW: https://www.postgresql.org/docs/current/postgres-fdw.html

First we need to register the extension to expose the functionality:
`CREATE EXTENSION postgres_fdw;`

Now we can register a foreign table:
```
CREATE SERVER foreign_server
        FOREIGN DATA WRAPPER postgres_fdw
        OPTIONS (host '192.83.123.89', port '5432', dbname 'foreign_db');
```

We can adapt this example:
```
CREATE SERVER child_ip_foreign_server
        FOREIGN DATA WRAPPER postgres_fdw
        OPTIONS (host '<child_pi_hostname>', port '5432', dbname 'child_IP_db'); -- we need to figure out how we are assigning IPs or host names... .
```

**Comment by smathermather** [comment]
Finally, we actually create what we wanted in the first place: a foreign table from our foreign server to access locally:

```
CREATE FOREIGN TABLE foreign_table (
        id integer NOT NULL,
        data text
)
        SERVER foreign_server
        OPTIONS (schema_name 'some_schema', table_name 'some_table');
```

Which, customized for us might be:

```
CREATE FOREIGN TABLE foreign_table (
	photoid BIGINT
	,projectid BIGINT
	,survey_run text NOT NULL
	,device text NOT NULL
	,photo_filename text NOT NULL
	,photo BYTEA NOT NULL
	,thumbnail BYTEA
)
        SERVER foreign_server
        OPTIONS (schema_name 'public', table_name 'cameras');
```

**Comment by hcwinsemius** [comment]
I checked this out. Am I right that all of this shoukd occur on parent side? I have three questions.

Am I correct that we'll need to make 7 of these servers and tables if we have 7 picams? And give each of these a different name?

How do you then merge these tables together?

And finally: what happens if you shutdown devices? Do you then automatically loose that table?

And maybe more finally. How do you extract files from this (query)?

**Comment by smathermather** [comment]
Perfect set of questions:
> Am I correct that we'll need to make 7 of these servers and tables if we have 7 picams? And give each of these a different name?

Correct

> How do you then merge these tables together?
```
CREATE MATERIALIZED VIEW photos
SELECT * FROM foreign_table_name1
    UNION
SELECT * FROM foreign_table_name2
     UNION
SELECT * FROM foreign_table_name3
```

**Comment by smathermather** [comment]
Closed with https://github.com/OpenDroneMap/odm360/pull/101

**Comment by hcwinsemius** [comment]
@smathermather I have tried the recipe just with postgres as user and within psql interactive prompt. I got to this point:
```
odm360=# CREATE USER MAPPING
    FOR postgres
 SERVER pi1_foreign
OPTIONS (user 'odm360', password 'zanzibar');^C
odm360=# select * from pi1_foreign_table;
ERROR:  could not connect to server "pi1_foreign"
DETAIL:  could not connect to server: Connection refused
	Is the server running on host "192.168.178.1" and accepting
	TCP/IP connections on port 5432?
```
The server is definitely on that ip address and the port seems to be default. I can also see the table with ```\detr```, so not sure why it can't be accessed.

**Comment by smathermather** [comment]
Yup. It's running there, but you can't get to it because by default PostgreSQL isn't accessible beyond localhost.
https://blog.bigbinary.com/2016/01/23/configure-postgresql-to-allow-remote-connection.html

**Comment by smathermather** [comment]
> The server is definitely on that ip address and the port seems to be default. I can also see the table with `\detr`, so not sure why it can't be accessed.

Fixed here: https://github.com/OpenDroneMap/odm360/pull/107
