### ISSUE TITLE
Naming of Pis

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/odm360#62]
As network connected devices that have cards that can be swapped around, we need some approaches WRT naming devices.

Current thinking (if I can remember this morning's call):

1. MicroSD cards will be the root of the pi cameras' identities. In that way, data on the pis will follow the identity
1. DHCP will be used for assigning ips, so the pi identity is the important factor in registering the foreign table in the database
1. ... How are we handling domain names? Are we using `<pi_id>.local`? If so, we need to ensure that we don't create broadcast storms in communications with each of the pis. Otherwise, we need a way to track local DNS entries. We can set up a DNS server, or just track them in `/etc/hosts` on the parent pi.

**Comment by smathermather** [comment]
I am wondering if we should just use mDNS: https://en.wikipedia.org/wiki/Multicast_DNS

**Comment by smathermather** [comment]
Ok, mDNS is the way to go. It will need added to the deployment scripts:
https://www.howtogeek.com/167190/how-and-why-to-assign-the-.local-domain-to-your-raspberry-pi/

Add `sudo apt-get install avahi-daemon` to the deployment scripts. Add `.local` to the name of the device, and Bob's your uncle.

**Comment by hcwinsemius** [comment]
Each device now gets a uuid in database upon provisioning.

**Comment by smathermather** [comment]
Ok, but does this get set in the local `/etc/hostname` and I don't think we are yet using mDNS to handle naming across the network.

**Comment by hcwinsemius** [comment]
No it doesn't. Maybe I am overlooking something. Why would we need hostname to have a uuid? I am using the uuid to recognize which device is online and which photo belongs to which device. It is stored upon provisioning in the child database and retrieved upon starting the child. So I have a fixed uuid available and don't really see a reason to have a uuid name for the hostname as well.

I am pretty sure I am overlookig something. So what do we need it for?

H

**Comment by smathermather** [comment]
We can't and shouldn't rely on IPs for communication. We need host names. There are a lot of mechanisms for choosing hostnames, but one approach would be to use `<uuid>`.local that matches the internal `uuid` and install mDNS. This ensures that if the IP address changes, communications can continue using the name.

**Comment by hcwinsemius** [comment]
For http requests it is not a problem if ip addresses change. Also in the
database this is not a problem as the views are generated on the fly when
devices come online. Can you clarify in which operation we still need a
fixed name for communication?

Op zo 11 okt. 2020 16:17 schreef Stephen Mather <notifications@github.com>:

**Comment by smathermather** [comment]
Database: If a DHCP lease expires while the pi0s are connected, the reference on the parent pi for FDW will become wrong, as it points to an address that has now changed.

**Comment by smathermather** [comment]
I've got a branch here to implement (split off your foreign tables branch):
https://github.com/OpenDroneMap/odm360/tree/pi_naming

It just needs me to extract the UUID name and add to hostname, but it's time for a zoom call...

**Comment by smathermather** [comment]
I don't think we finished this: the pis have mDNS installed, but they are not getting the correct hostname yet.

**Comment by smathermather** [comment]
NM. I found where this is happening. Closing again.
