### ISSUE TITLE
Change primary branch to main

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/odm360#76]
Per acknowledged issues with branch naming conventions, we should change the primary branch to `main`. I have done this already, but will wait a few days before removing the `master` branch. They are identical at this time.

**Comment by ivangayton** [comment]
Wholeheartedly agree. I have already switched my local tracking to main, and deleted master from my local repos. From where I'm standing, you can remove master anytime you like.

**Comment by hcwinsemius** [comment]
I'm on main too. If you want to remove, go ahead.

**Comment by smathermather** [comment]
Cool. Removed.
