### ISSUE TITLE
child provisioning 256 mb GPU RAM and picamera activated

### ISSUE THREAD

**Issue by hcwinsemius** [OpenDroneMap/odm360#78]

**Comment by smathermather** [comment]
I think we just add the following to the pi0's config.txt:
```
start_x=1             # Enables camera
gpu_mem=256           # Sets GPU memory
```

**Comment by smathermather** [comment]
My little addition to the provisioning scripts is not yet tested:
https://github.com/OpenDroneMap/odm360/pull/79

**Comment by smathermather** [comment]
This is implemented and tested with https://github.com/OpenDroneMap/odm360/pull/85
