### ISSUE TITLE
Address image directory structure

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/odm360#8]
Current directory structure puts photos in a sequence in directories according to camera:
![image](https://user-images.githubusercontent.com/1174901/84776339-2fd6d480-afae-11ea-958e-469bf51381ce.png)

We need an approach which instead treats sequences as projects for upload to WebODM api.

**Comment by hcwinsemius** [comment]
@smathermather I am more or less at the stage to think about logical structuring of folders. Can you recommend or giva an example of folder structure that would be most ideal for ODM?

**Comment by smathermather** [comment]
The structure is pretty straight forward: each sequence that we want to process together (each logical sequence) needs to be uploaded in one go to a NodeODM instance, per [POST /task/new](https://github.com/OpenDroneMap/NodeODM/blob/master/docs/index.adoc#post-tasknew) proceedure.

I imagine a process similar to the following: person in the field triggers the start of a sequence to be stitched together as a single 3D reconstruction. At the end of that sequence the trigger a button to stop the collection of the sequence. That sequence needs organized in a way where when we trigger upload to NodeODM, it all goes as a single zip file.

The simplest way to organize this is that for each logical sequence, we dump them all in the same directory. Alternatively, we simply track what is all part of one sequence and zip up those images into a single zip when it's time to send them to the Node.
