### ISSUE TITLE
Bring images into database 𝚏̶𝚒̶𝚕̶𝚎̶-̶𝚋̶𝚊̶𝚜̶𝚎̶𝚍̶ ̶𝚟̶𝚒̶𝚊̶ ̶𝚖̶𝚞̶𝚕̶𝚝̶𝚒̶𝚌̶𝚘̶𝚛̶𝚗̶

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/odm360#86]
To replicate:

* Do normal setup
* Setup for child pi
* Run child database script 
* Then examples/photo_bytes.py

Via @hcwinsemius:
> I nailed it now, to where it goes wrong. If I simply read the byte stream (without writing to database) it works fine! It is storing of the byte stream into the database that makes things awfully slow
> It takes 30 seconds to store one photo of about 5 mb
> Unacceptable!

**Comment by smathermather** [comment]
Thoughts on possible fixes:
* Increase shared_buffers. As this is already 128MB, this probably isn't the issue
* Increase work_mem. This is defaulting to 4MB and the images are 5MB, so we are immediately going to disk rather than working in memory as long as performance dictates. Suggest we try changing this to 10MB
* If this doesn't work, something drastic like: File System FDW: https://multicorn.readthedocs.io/en/latest/foreign-data-wrappers/fsfdw.html?

**Comment by hcwinsemius** [comment]
I tried to temporarily increase work mem by adding:

```SET work_mem = '24MB';```

at the beginning of the sql command and

```RESET work_mem;```

at the end. To no avail unfortunately.....

**Comment by smathermather** [comment]
Leaning toward File System FDW, since writing to the file system is fast. Will work on example shortly.

**Comment by smathermather** [comment]
Multicorn gives us issues with the foreign table on the parent. An alternate recipe is to do the following:
* Ensure logging is turned off on the table
    * `ALTER TABLE "photos_child" SET UNLOGGED;`
* Save image to disk in a location readable by postgres
* Load image
     * `insert into ptest(photo) values(pg_read_binary_file('/tmp/atticlight.jpg'));`

We can retrieve a lower resolution version of image if needed, as we will likely resize in OpenDroneMap anyway.

**Comment by hcwinsemius** [comment]
We moved to a normal table now. I have also a provisioning for automated hostname renaming using the device uuid. @smathermather I am considering to make a combined view as follows. Please comment:

- when starting delete any existing server and foreign table or view left from a previous session.
- when devices come online, simply collect their uuid in the devices table (this already happens).

- when a user clicks on the files page, a set of filters appears for filtering on project and survey_run. The projects and survey runs available are queried from the 'projects' table  at this stage no foreign table exists and no foreign server exists.

When a user has selected a project and survey (or all surveys belonging to one project) only then are foreign tables built from all available children and queried for filenames. The amount will be quite large so I propose that we show per device how many files are available in a simple table. If there are fewer devices online than there should be given the rig size belonging to the query, then an error will be returned instead.

- if the query was successful the 'download' button becomes active and user can finally download a zipfile with the results.

Please comment!
